### ISSUE TITLE
Undefined Behavior when T contains uninit bytes

### ISSUE THREAD

**Issue by TyPR124** [Lucretiel/stowaway#3]
Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d75fb532da27fbb22467a2b3b9439119

Use Tools -> Miri, it detects undefined behavior in Stowaway::new.

**Comment by TyPR124** [comment]
It appears that unconditionally using MaybeUninit::zeroed() in Stowaway::new() is enough to fix this.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1a880674c2154bc3e70aef1bf4ae5d36

**Comment by Lucretiel** [comment]
Ah, yes, I was a bit worried about this. I guess those bytes are allowed to be uninit even though they're still "read" whenever the structure is copied, because they're never "used".
