### ISSUE TITLE
Undefined Behavior when T is zero-sized

### ISSUE THREAD

**Issue by TyPR124** [Lucretiel/stowaway#5]
https://github.com/Lucretiel/stowaway/blob/fb1d8d1e658d87d23ed6541bfed96850eeca2f50/src/lib.rs#L212-L217

https://github.com/Lucretiel/stowaway/blob/fb1d8d1e658d87d23ed6541bfed96850eeca2f50/src/lib.rs#L283

Per ptr::read: Note that even if T has size 0, the pointer must be non-NULL and properly aligned.

https://doc.rust-lang.org/std/ptr/fn.read.html

**Comment by TyPR124** [comment]
I also want to point out that this is very much NOT fine, as ALL references must be non-null.

https://github.com/Lucretiel/stowaway/blob/fb1d8d1e658d87d23ed6541bfed96850eeca2f50/src/lib.rs#L537-L540

https://github.com/Lucretiel/stowaway/blob/fb1d8d1e658d87d23ed6541bfed96850eeca2f50/src/lib.rs#L547

**Comment by Lucretiel** [comment]
> I also want to point out that this is very much NOT fine, as ALL references must be non-null.

Are you certain this is the case? This contradicts the [nomicon](https://doc.rust-lang.org/nomicon/vec-zsts.html#allocating-zero-sized-types):

> So if the allocator API doesn't support zero-sized allocations, what on earth do we store as our allocation? `Unique::empty()` of course! Almost every operation with a ZST is a no-op since ZSTs have exactly one value, and therefore no state needs to be considered to store or load them. This actually extends to `ptr::read` and `ptr::write`: they won't actually look at the pointer at all. As such we never need to change the pointer.

**Comment by Lucretiel** [comment]
Opened https://github.com/rust-lang/nomicon/issues/198

**Comment by TyPR124** [comment]
Not at a computer, but I'm pretty sure if you look into the Unique::empty
implementation, it actually does create a properly aligned pointer. Feel
free to correct me if I'm wrong, but that is what I remember from looking
at it myself in the past.

**Comment by TyPR124** [comment]
https://github.com/rust-lang/rust/blob/fb29dfcc9ada6ed10308b6e7f405569f61a9af0b/src/libcore/ptr/unique.rs#L76

**Comment by TyPR124** [comment]
Also from the nomicon https://doc.rust-lang.org/nomicon/exotic-sizes.html

Note that references to ZSTs (including empty slices), just like all other
references, must be non-null and suitably aligned. Dereferencing a null or
unaligned pointer to a ZST is undefined behavior
<https://doc.rust-lang.org/nomicon/what-unsafe-does.html>, just like for
any other type.

**Comment by TyPR124** [comment]
Here is an assembly comparison between Box and Stowaway using `mem::align_of::<T>()` for ZSTs, per discussion in #4.

https://rust.godbolt.org/z/cFsRij
